version: "2"
services:
  quiz:
      image: quizart-ui:0.1.0
      build: './quizztack-ui'
      expose:
        - 8081
      links:
        - db
        - redis
      environment:
         MONGO_URL: 'mongodb://db/quizztack-uiDB'
         REDIS_URL: 'redis://redis'
      networks:
        - front-tier
        - back-tier
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
  db:
    image: mongo:3.0.14
    ports:
      - 27017:27017
    networks:
      - back-tier
  redis:
    image: redis:3.0.7
    ports:
      - 6379:6379
    networks:
      - back-tier
  lb:
    image: dockercloud/haproxy:1.2.1
    ports:
      - 80:80
    links:
      - quiz
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
